### ISSUE TITLE
Diagrama Entidad Relacion

### ISSUE THREAD

**Issue by ingcdsantamaria** [ingcdsantamaria/Degorra#12]
Se estudiará y realizará su respectivo diagrama de entidad relacion con el fin de un mejor manejo de la base de datos.

**Comment by djvalderrama67** [comment]
Diagrama de entidad de relacion subido

**Comment by djvalderrama67** [comment]
Ajustando las relaciones

**Comment by djvalderrama67** [comment]
El diagrama esta completo
